server:
   port: 80
   servlet:
      context-path: /
debug:
    true      

springfox.documentation.swagger.v2.path: /docs
logging:
    level: 
       org.springframework: ERROR
elk:
    ip : 0
    porta : 0
    
   